### ISSUE TITLE
luaotfload error

### ISSUE THREAD

**Issue by kiryph** [poppyschmo/deoplete-latex#2]
I have encountered following error:
![deoplete-latex-error-luaotfload](https://cloud.githubusercontent.com/assets/371756/22645682/86642968-ec68-11e6-8184-29859bcaa6d3.png)

It does look like the script has an issue with '\usepackage{luaotfload}'.

**Comment by poppyschmo** [comment]
> It does look like the script has an issue with '\usepackage{luaotfload}'.

Amazingly, *any* unrecognized package produces this error. Sad, but not altogether shocking that I failed to include a check for this in the tests. Just pushed a patch that appears to quiet things, but I should probably reason through it properly before closing this out. Thanks.
