### ISSUE TITLE
Exception during latex.on_event for event 'Init' on unknown package

### ISSUE THREAD

**Issue by stephanlukasczyk** [poppyschmo/deoplete-latex#4]
I have a LaTeX document using the 2017 version of the ACM document style, namely the `acmart` class. The `acmart.cls` is in the same folder as my `main.tex`—compilation with pdfLaTeX works perfectly fine.

Nevertheless, when opening the file in neovim (latest git) with latest deoplete and latest deoplete-latex yields the following stack trace (from neovim's `:messages`):
```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/sl/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 468, in on_event
[deoplete]     source.on_event(context)
[deoplete]   File "/home/sl/.vim/bundle/deoplete-latex/rplugin/python3/deoplete/sources/deoplete_latex.py", line 167, in on_event
[deoplete]     witgroups = dict(self._find_packages())
[deoplete]   File "/home/sl/.vim/bundle/deoplete-latex/rplugin/python3/deoplete/sources/deoplete_latex.py", line 158, in _find_packages
[deoplete]     'class' in m.group(1) else m.group(3)), m.group(2)
[deoplete] KeyError: 'acmart'
[deoplete] Exception during latex.on_event for event 'Init': 'acmart'.  Use :messages for error details.
```
I guess that this occurs because the class is not known to deoplete-latex, somehow. But how can one fix this?

**Comment by stephanlukasczyk** [comment]
If I interpret e29b5d1551f50982d6e6b6af20d0f07f2ac6224a correctly, you won't continue support for this plugin because vimtex can do everything?
Otherwise, I would appreciate a fix very much.

**Comment by poppyschmo** [comment]
> .., you won't continue support for this plugin because vimtex can do everything?

Unless there's some compelling reason not to, this seems only sane. But, apologies for not posting the redirect notice sooner (vimtex has actually had this capability for many months). Regarding your issue, I'll be raiding this plugin for something unrelated. If a fix presents itself, I'll push it, but no guarantees. Thanks.

**Comment by stephanlukasczyk** [comment]
I understand your argument, thanks for clearification. I now switch to only use VimTeX without deoplete-latex, which works fine. Maybe the author of deoplete, @Shougo, could remove the plugin in his list of completion sources, as VimTeX seems to be fine…

I close this issue, thanks for your reply.

**Comment by Shougo** [comment]
I have removed deoplete-latex from the list.
